# Generated by Django 5.2.3 on 2025-07-17 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Статус оборудования', max_length=256)),
                ('description', models.TextField(blank=True, help_text='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название типа оборудования', max_length=256)),
                ('description', models.TextField(blank=True, help_text='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Краткое название площадки', max_length=256)),
                ('adress', models.TextField(help_text='Полный адрес нахождения площадки')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название оборудования', max_length=256)),
                ('accounting_name', models.TextField(help_text='Наименование по бухгалтерии')),
                ('serial_number', models.CharField(help_text='Серийный или заводской номер', max_length=256)),
                ('inventory_number', models.CharField(help_text='Инвентарный номер', max_length=256)),
                ('description', models.TextField(blank=True, help_text='Описание')),
                ('status', models.ForeignKey(help_text='Выберите статус оборудования', on_delete=django.db.models.deletion.PROTECT, to='main.equipmentstatus')),
                ('equipment_type', models.ForeignKey(help_text='Выберите тип оборудования', on_delete=django.db.models.deletion.PROTECT, to='main.equipmenttype')),
                ('office', models.ForeignKey(help_text='Выберите площадку размещения оборудования', on_delete=django.db.models.deletion.PROTECT, to='main.office')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
