# Generated by Django 5.2.3 on 2026-02-14 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='managers',
            field=models.ManyToManyField(related_name='managed_offices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='accounting_name',
            field=models.TextField(help_text='Наименование по бухгалтерии', verbose_name='Наименование по бухгалтерии'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='description',
            field=models.TextField(blank=True, help_text='Описание', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.ForeignKey(help_text='Выберите тип оборудования', on_delete=django.db.models.deletion.PROTECT, to='main.equipmenttype', verbose_name='Тип оборудования'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='inventory_number',
            field=models.CharField(help_text='Инвентарный номер', max_length=256, verbose_name='Инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(help_text='Название оборудования', max_length=256, verbose_name='Название оборудования'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='office',
            field=models.ForeignKey(help_text='Выберите площадку размещения оборудования', on_delete=django.db.models.deletion.PROTECT, to='main.office', verbose_name='Площадка'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(help_text='Серийный или заводской номер', max_length=256, verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.ForeignKey(help_text='Выберите статус оборудования', on_delete=django.db.models.deletion.PROTECT, to='main.equipmentstatus', verbose_name='Статус'),
        ),
    ]
