# Generated by Django 5.2.3 on 2026-03-15 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_office_managers_alter_equipment_accounting_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='in_work_date',
            field=models.DateField(blank=True, default=datetime.date(1777, 7, 7), help_text='Дата ввода в эксплуатацию', verbose_name='Дата ввода в эксплуатацию'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='warranty_date',
            field=models.DateField(blank=True, default=datetime.date(1777, 7, 7), help_text='Дата окончания гарантии', verbose_name='Дата окончания гарантии'),
        ),
    ]
