# Generated by Django 5.2.3 on 2026-03-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_equipment_in_work_date_equipment_warranty_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Производитель', max_length=256)),
                ('description', models.TextField(blank=True, help_text='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='ModelName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Модель', max_length=256)),
                ('description', models.TextField(blank=True, help_text='Описание')),
            ],
        ),
    ]
