# Generated by Django 5.2.3 on 2026-03-15 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_manufacturer_modelname'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='manufacturer',
            field=models.ForeignKey(blank=True, help_text='Выберите производителя', null=True, on_delete=django.db.models.deletion.PROTECT, to='main.manufacturer', verbose_name='Производитель оборудования'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='model',
            field=models.ForeignKey(blank=True, help_text='Выберите модель', null=True, on_delete=django.db.models.deletion.PROTECT, to='main.modelname', verbose_name='Модель оборудования'),
        ),
    ]
