# Generated by Django 5.2.3 on 2026-03-15 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_equipment_manufacturer_equipment_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='in_work_date',
            field=models.DateField(blank=True, default=datetime.date(1987, 8, 11), help_text='Дата ввода в эксплуатацию', verbose_name='Дата ввода в эксплуатацию'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='warranty_date',
            field=models.DateField(blank=True, default=datetime.date(1987, 8, 11), help_text='Дата окончания гарантии', verbose_name='Дата окончания гарантии'),
        ),
    ]
