# Generated by Django 5.2.3 on 2026-03-15 19:44

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_equipment_in_work_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='СonsumableType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название типа расходника', max_length=256)),
                ('description', models.TextField(blank=True, help_text='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Сonsumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название расходника', max_length=256, verbose_name='Название расходника')),
                ('accounting_name', models.TextField(help_text='Наименование по бухгалтерии', verbose_name='Наименование по бухгалтерии')),
                ('in_work_date', models.DateField(blank=True, default=datetime.date(1987, 8, 11), help_text='Дата ввода в эксплуатацию', verbose_name='Дата ввода в эксплуатацию')),
                ('warranty_date', models.DateField(blank=True, default=datetime.date(1987, 8, 11), help_text='Дата окончания гарантии', verbose_name='Дата окончания гарантии')),
                ('description', models.TextField(blank=True, help_text='Описание', verbose_name='Описание')),
                ('manufacturer', models.ForeignKey(blank=True, help_text='Выберите производителя', null=True, on_delete=django.db.models.deletion.PROTECT, to='main.manufacturer', verbose_name='Производитель расходника')),
                ('model', models.ForeignKey(blank=True, help_text='Выберите модель', null=True, on_delete=django.db.models.deletion.PROTECT, to='main.modelname', verbose_name='Модель расходника')),
                ('office', models.ForeignKey(help_text='Выберите площадку размещения расходника', on_delete=django.db.models.deletion.PROTECT, to='main.office', verbose_name='Площадка')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
