# Generated by Django 5.2.3 on 2026-03-15 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_сonsumabletype_сonsumable'),
    ]

    operations = [
        migrations.AddField(
            model_name='сonsumable',
            name='consumable_type',
            field=models.ForeignKey(blank=True, help_text='Выберите тип расходника', null=True, on_delete=django.db.models.deletion.PROTECT, to='main.сonsumabletype', verbose_name='Тип расходника'),
        ),
        migrations.AddField(
            model_name='сonsumable',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
    ]
