# Generated by Django 5.2.3 on 2026-03-15 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_сonsumable_consumable_type_сonsumable_count'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Сonsumable',
            new_name='Consumable',
        ),
    ]
