# Generated by Django 5.2.3 on 2026-03-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_сonsumable_consumable'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumable',
            name='write_off_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество списанного'),
        ),
    ]
