# Generated by Django 5.2.3 on 2026-03-19 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_consumable_write_off_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumable',
            options={'ordering': ['name'], 'verbose_name': 'Расходник', 'verbose_name_plural': 'Расходники'},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['name'], 'verbose_name': 'Оборудование', 'verbose_name_plural': 'Оборудование'},
        ),
        migrations.AlterModelOptions(
            name='equipmentstatus',
            options={'verbose_name': 'Статус оборудования', 'verbose_name_plural': 'Статусы оборудования'},
        ),
        migrations.AlterModelOptions(
            name='equipmenttype',
            options={'verbose_name': 'Тип оборудования', 'verbose_name_plural': 'Типы оборудования'},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'verbose_name': 'Производитель', 'verbose_name_plural': 'Производители'},
        ),
        migrations.AlterModelOptions(
            name='modelname',
            options={'verbose_name': 'Модель', 'verbose_name_plural': 'Модели'},
        ),
        migrations.AlterModelOptions(
            name='office',
            options={'verbose_name': 'Площадка', 'verbose_name_plural': 'Площадки'},
        ),
        migrations.AlterModelOptions(
            name='сonsumabletype',
            options={'verbose_name': 'Тип расходного материала', 'verbose_name_plural': 'Типы расходных материалов'},
        ),
    ]
