# Generated by Django 5.2.3 on 2026-03-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_consumable_options_alter_equipment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumable',
            name='description',
            field=models.TextField(blank=True, help_text='Описание', null=True, verbose_name='Описание'),
        ),
    ]
