# Generated by Django 5.2.3 on 2026-03-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_consumable_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumable',
            name='room',
            field=models.TextField(blank=True, help_text='В каком помещении находится расходник', verbose_name='Помещение'),
        ),
    ]
