# Generated by Django 5.2.3 on 2026-03-26 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_consumable_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Тип ОЗУ', max_length=256)),
            ],
            options={
                'verbose_name': 'Тип ОЗУ',
                'verbose_name_plural': 'Типы ОЗУ',
            },
        ),
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Операционная система', max_length=256)),
            ],
            options={
                'verbose_name': 'Операционная система',
                'verbose_name_plural': 'Операционные системы',
            },
        ),
        migrations.CreateModel(
            name='StorageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Тип накопителя', max_length=256)),
            ],
            options={
                'verbose_name': 'Тип накопителя',
                'verbose_name_plural': 'Типы накопителей',
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='additional_equipment',
            field=models.CharField(blank=True, help_text='Дополнительное оборудование в комплекте', max_length=256, verbose_name='Дополнительное оборудование'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='memory_size',
            field=models.PositiveIntegerField(default=0, verbose_name='Объем ОЗУ'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='room',
            field=models.TextField(blank=True, help_text='В каком помещении находится расходник', verbose_name='Помещение'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='storage_size',
            field=models.PositiveIntegerField(default=0, verbose_name='Объем накопителя'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='memory_type',
            field=models.ForeignKey(blank=True, help_text='Выберите тип ОЗУ', null=True, on_delete=django.db.models.deletion.PROTECT, to='main.memorytype', verbose_name='Тип ОЗУ'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='operating_system',
            field=models.ForeignKey(blank=True, help_text='Выберите тип ОС', null=True, on_delete=django.db.models.deletion.PROTECT, to='main.operatingsystem', verbose_name='Тип ОС'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='storage_type',
            field=models.ForeignKey(blank=True, help_text='Выберите тип накопителя', null=True, on_delete=django.db.models.deletion.PROTECT, to='main.storagetype', verbose_name='Тип накопителя'),
        ),
    ]
