# Generated by Django 5.2.3 on 2026-03-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_memorytype_operatingsystem_storagetype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='additional_equipment',
            field=models.TextField(blank=True, help_text='Дополнительное оборудование в комплекте', verbose_name='Дополнительное оборудование'),
        ),
    ]
