# Generated by Django 5.2.3 on 2026-03-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_equipment_additional_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumable',
            name='room',
            field=models.CharField(blank=True, help_text='В каком помещении находится расходник', max_length=256, verbose_name='Помещение'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='room',
            field=models.CharField(blank=True, help_text='В каком помещении находится оборудование', max_length=256, verbose_name='Помещение'),
        ),
    ]
