# Generated by Django 5.2.3 on 2026-03-29 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_consumable_room_alter_equipment_room'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='СonsumableType',
            new_name='ConsumableType',
        ),
    ]
