# Generated by Django 5.2.3 on 2026-03-29 19:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_rename_сonsumabletype_consumabletype'),
    ]

    operations = [
        migrations.CreateModel(
            name='WriteOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('writeoff_date', models.DateField(default=datetime.date.today, help_text='Дата списания', verbose_name='Дата списания')),
                ('who_writeoff', models.CharField(help_text='Кем списывается расходник', max_length=256, verbose_name='Кем списывается расходник')),
                ('action_type', models.CharField(choices=[('IN', 'установке'), ('UP', 'модернизации')], default='IN', max_length=2)),
                ('which_equipment', models.CharField(help_text='для какого устройства', max_length=256, verbose_name='для какого устройства')),
                ('used_by', models.CharField(help_text='Кем используется оборудование', max_length=256, verbose_name='Кем используется оборудование')),
                ('who_made_work', models.CharField(help_text='Работу сдал:', max_length=256, verbose_name='Работу сдал:')),
                ('who_take_work', models.CharField(help_text='Работу принял(а):', max_length=256, verbose_name='Работу принял(а):')),
                ('consumable', models.ForeignKey(help_text='Выберите расходник для списания', on_delete=django.db.models.deletion.PROTECT, to='main.consumable', verbose_name='Списание расходника')),
            ],
            options={
                'verbose_name': 'Списание',
                'verbose_name_plural': 'Списания',
                'ordering': ['consumable'],
            },
        ),
    ]
