# Generated by Django 5.2.3 on 2026-06-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_writeoff'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumable',
            name='nomenclature',
            field=models.CharField(default='', help_text='Номенклатура', max_length=256, verbose_name='Номенклатура'),
        ),
        migrations.AddField(
            model_name='consumable',
            name='real_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Фактическое количество'),
        ),
    ]
