# Generated by Django 5.2.3 on 2026-06-09 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_consumable_nomenclature_consumable_real_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmenttype',
            options={'ordering': ['name'], 'verbose_name': 'Тип оборудования', 'verbose_name_plural': 'Типы оборудования'},
        ),
    ]
