# Generated by Django 5.2.3 on 2026-06-09 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_equipmenttype_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumabletype',
            options={'ordering': ['name'], 'verbose_name': 'Тип расходного материала', 'verbose_name_plural': 'Типы расходных материалов'},
        ),
        migrations.AlterModelOptions(
            name='equipmentstatus',
            options={'ordering': ['name'], 'verbose_name': 'Статус оборудования', 'verbose_name_plural': 'Статусы оборудования'},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'ordering': ['name'], 'verbose_name': 'Производитель', 'verbose_name_plural': 'Производители'},
        ),
        migrations.AlterModelOptions(
            name='memorytype',
            options={'ordering': ['name'], 'verbose_name': 'Тип ОЗУ', 'verbose_name_plural': 'Типы ОЗУ'},
        ),
        migrations.AlterModelOptions(
            name='modelname',
            options={'ordering': ['name'], 'verbose_name': 'Модель', 'verbose_name_plural': 'Модели'},
        ),
        migrations.AlterModelOptions(
            name='office',
            options={'ordering': ['name'], 'verbose_name': 'Площадка', 'verbose_name_plural': 'Площадки'},
        ),
        migrations.AlterModelOptions(
            name='operatingsystem',
            options={'ordering': ['name'], 'verbose_name': 'Операционная система', 'verbose_name_plural': 'Операционные системы'},
        ),
        migrations.AlterModelOptions(
            name='storagetype',
            options={'ordering': ['name'], 'verbose_name': 'Тип накопителя', 'verbose_name_plural': 'Типы накопителей'},
        ),
    ]
